### ISSUE TITLE
Make milestone and issues from design

### ISSUE THREAD

**Issue by Valyukhov** [hiscoder-com/glokas#11]
1. Make milestones
2. Calculate
3. Make issues in project

**Comment by Valyukhov** [comment]
From Paul:
1) Верхняя панель с логотипом Glokas и именем пользователя
2) Боковая панель слева с навигацией, информацией, Log out
3) Основная рабочая область справа
4) Разработка системы учета использования (Used/Remaining/Days left)
5) модальное окна для ввода URL видео
6) Реализация функции парсинга URL видео
7) Настройка подключения к YouTube API
8) Отображение превью и заголовка видео
9) Создание компонента для отображения описания видео
10) Реализация функции выбора языков для перевода
11) Добавление функции поиска языков
12) Разработка модального окна для подтверждения перевода
13) Реализация логики расчета количества слов и стоимости перевода
14) Создание функции подсчета использованных и оставшихся слов
15) Создание функции сохранения результатов перевода
16) Реализация проверки на достаточное количество слов для перевода
17) Добавление подсказок и вспомогательного текста
18) Добавление уведомлений об успешном выполнении операций
19) Реализация выпадающего меню для выбора языков перевода
20) Реализация выпадающего меню для выбора языков перевода
21) Создание модального окна для редактирования перевода каждого языка отдельно
22) Реализация раздельного редактирования заголовка и описания для каждого языка
23) Добавление функции удаления языков с подтверждением
24) Реализация сворачиваемых секций для языков перевода
25) Добавление кнопки "View all" для просмотра полного описания видео
26) Реализация функции "Select language" в нижней части страницы
27) Отображение даты последнего обновления перевода

**Comment by Pavel064** [comment]
1) страница авторизация/регистрация
2) сайдбар и аппбар (лого, основные разделы, система учета использования (Used/Remaining/Days left), кнопка выхода из аккаунта, имя юзера )
3) рабочее пространство (YouTube Automatization)
3.1) парсер + модалка
3.2) Отображение превью и заголовка видео
3.3) выбор языков для перевода
3.4) модальное окно для подтверждения перевода
3.5) таблица со списком языков, мультиселектом и поиском по списку
3.6) редактирование выбранного языка в модальном окне
3.7) модальное окно с подтверждением удаления языка
3.8) кнопка "View all", это модалка с Video Description in English
4) раздел "All video"
5) раздел "Settings"
