### ISSUE TITLE
YouTube Parser

### ISSUE THREAD

**Issue by Valyukhov** [hiscoder-com/glokas#13]
Research how we can parse Youtube

List items that we need parse:

Video title
Video Description
Thumbnail (link, dimensions)
Default video language
A list of which videos have already been localized to (language name, translated title, translated description)

Plan

1. Сделать кнопку аутентификации. По клику мы получаем доступ к youtube аккаунту пользователя. 
2. После успешной авторизации появляется список всех видео, которые загрузил пользователь в ютуб.
3. Клик по любому видео открывает страницу видео, где вы водятся поля, что прописаны выше.
4. Так же тут три инпута (язык, тайтл, дескрипшн) и кнопка. Если их заполнить и нажать кнопку сохранить, то в ютубе сохраняются данные локализации видео.

- Нужно узнать, как именно происходит вход, это вход в аккаунт гугл или же отдельный вход через ютуб?
- Там есть какая-то квота на апи запросы. Нужно приблизительно подстчитать, сможем ли мы использовать апи? Квота на приложение или на каждого юзера?

**Comment by Valyukhov** [comment]
@foxprogs could you please add description and your technical vision for this issue?

**Comment by DenisArger** [comment]
<html xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:w="urn:schemas-microsoft-com:office:word"
xmlns:m="http://schemas.microsoft.com/office/2004/12/omml"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Word.Document>
<meta name=Generator content="Microsoft Word 15">
<meta name=Originator content="Microsoft Word 15">
<link rel=File-List
href="file:///C:\Users\User\AppData\Local\Temp\msohtmlclip1\01\clip_filelist.xml">

<link rel=themeData
href="file:///C:\Users\User\AppData\Local\Temp\msohtmlclip1\01\clip_themedata.thmx">
<link rel=colorSchemeMapping
href="file:///C:\Users\User\AppData\Local\Temp\msohtmlclip1\01\clip_colorschememapping.xml">

<style>

</style>

</head>

<body lang=RU style='tab-interval:35.4pt'>



  |   |  
-- | -- | --
  |   |  
  |   |  
  |   |  
  |   |  
  |   |  




</body>

</html>

**Comment by DenisArger** [comment]
![изображение](https://github.com/user-attachments/assets/6b1fb3fd-dd2d-4815-91f9-c30acd7bb49a)

Выводы:
- минимальное количество затраченных квот за один алгоритм обновления - 50 квот. При условии, что раннее была получена информация и все поля были корректно заполнены
- минимальное количество затраченных квот за один алгоритм обновления - 54 квот. Это случай, когда нужно получить полную информацию по видео и поле с категорией видео не было заполнено.


В сутки можно потратить 10к квот.
10 000 / 50 = 200.
Максимальное количество видео, которое можно обработать в сутки равно 200.

10 000 / 54 = 185.
Минимальное количество видео, которое можно обработать  в сутки  равно 185.


М

**Comment by DenisArger** [comment]
Информация по квотам:
https://developers.google.com/youtube/v3/determine_quota_cost

Замечено, что квота не списывается моментально. Приходиться ждать пару минут. Особенно ощутимо при обновлении информации.
